name "drupal"
description "Installs Drupal"
license "BSD"
maintainer "Stephen Crawley"
maintainer_email "s.crawley at uq dot edu dot au"

depends "mysql"
depends "apache2"
depends "database"
depends "php"
depends "lamp"
depends "setup", ">= 1.3"
depends "drush"
supports "ubuntu"
