name "drupal"
description "Installs Drupal"
license "BSD"
maintainer "Stephen Crawley"
maintainer_email "s.crawley at uq dot edu dot au"

depends "mysql"
depends "apache"
depends "database"
supports "ubuntu"
