<?php
// $Id: default.settings.php,v 1.51 2010/10/11 23:49:48 dries Exp $

/**
 * @file
 * Drupal database access settings
 *
 * (Generated by Chef via the 'drupal' cookbook.)
 */
<% 
   drupal = node['drupal']
   dbs = drupal['databases']
   dbs.each do |key, attrs|
     keys = /^([^\/]+)\/([^\/]+)$/.match(key)
     raise "Invalid database keys #{key}" unless keys
%>
$databases['<%= keys[1] %>']['<%= keys[2] %>'] = array(
<%   attrs.each do |attr, val| %>
  '<%= attr %>' => '<%= val %>', 
<%   end
%>
);
<% 
   end
%>
